[package]
name = "crm"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = {version = "0.13.1"}
sqlx = { version = "0.8", features = [ "runtime-tokio" ] }
dotenvy = "0.15"

[profile.dev.package.sqlx-macros]
opt-level = 3
